name: AzureLoginSample

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup
           
            # Parameters - fill these in before running the script!
            # =====================================================
            
            $workspaceName = "Dev-Fabric-workpace"      # The name of the workspace
            $commitMessage = "Saving the Data to GitHub"      # The commit message

            echo $workspaceName
            echo $commitMessage
            # End Parameters =======================================
            
            $global:baseUrl = "https://api.fabric.microsoft.com/v1" # Replace with environment-specific base URL. For example: "https://api.fabric.microsoft.com/v1"
            
            $global:resourceUrl = "https://api.fabric.microsoft.com"
            
            $global:fabricHeaders = @{}
            
            function SetFabricHeaders() {
            
                #Login to Azure
                #Connect-AzAccount | Out-Null
            
                # Get authentication
                #$fabricToken = (Get-AzAccessToken -ResourceUrl $global:resourceUrl).Token
                $fabricToken = (Get-AzAccessToken).Token
                
            	  echo $fabricToken
                $global:fabricHeaders = @{
                    'Content-Type' = "application/json"
                    'Authorization' = "Bearer {0}" -f 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InEtMjNmYWxldlpoaEQzaG05Q1Fia1A1TVF5VSIsImtpZCI6InEtMjNmYWxldlpoaEQzaG05Q1Fia1A1TVF5VSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81NWVhNjE5Ni03MGI5LTQ0MTEtOTJmNS0wNGE1NDc5MWYxMjAvIiwiaWF0IjoxNzEyODcyODIyLCJuYmYiOjE3MTI4NzI4MjIsImV4cCI6MTcxMjg3NzIzNCwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhXQUFBQW03Z0VzMjNlS0Q3ZHFXL3kwdVJQeTIzMU1WcndYNitaRm1WcUtsMWZpTWZ2cW9pNE5mSldRZTBYaDM1cGFIelQiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiMTk1MGEyNTgtMjI3Yi00ZTMxLWE5Y2YtNzE3NDk1OTQ1ZmMyIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJZYWRhdiIsImdpdmVuX25hbWUiOiJHb3BhbCIsImdyb3VwcyI6WyI4ODhmOTUwOS00MjdjLTQ3ZDItODlkNy0zNzQ3OGZhNmYyMDgiLCIzYTMyMDY2Ni0yYjMxLTQ1MmMtOTlmNS0zNDg5YjU4Nzc0MWYiLCI3NWFlZjliZS1hYThjLTQyOWMtYTM5ZC0xNzc5NzkxZTk3OGQiXSwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMzQuOTguMTk2LjE4OSIsIm5hbWUiOiJZYWRhdiwgR29wYWwiLCJvaWQiOiIyNTAyNGMxMC00ZjcyLTQyYjgtODJjMi04YjU0ODk3Y2QxYzciLCJwdWlkIjoiMTAwMzIwMDA4RUFGQTc0OCIsInJoIjoiMC5BVnNBbG1IcVZibHdFVVNTOVFTbFI1SHhJRVpJZjNrQXV0ZFB1a1Bhd2ZqMk1CUDVBSEkuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiUHRUdnVRSjhqa2pjcjlCODlKNHQtUXlWYTFBMXNHVTNrbWd5M19YTkpOVSIsInRpZCI6IjU1ZWE2MTk2LTcwYjktNDQxMS05MmY1LTA0YTU0NzkxZjEyMCIsInVuaXF1ZV9uYW1lIjoiZ29wYWwueWFkYXZAc3RyYXRhY2VudC5jb20iLCJ1cG4iOiJnb3BhbC55YWRhdkBzdHJhdGFjZW50LmNvbSIsInV0aSI6ImlwS09uZ0NOeUVhSmhBLWhLQlFRQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2FlIjoiMSIsInhtc19jYyI6WyJDUDEiXSwieG1zX2ZpbHRlcl9pbmRleCI6WyI5MSJdLCJ4bXNfcmQiOiIwLjQyTGxZQlJpakFZQSIsInhtc19zc20iOiIxIiwieG1zX3RjZHQiOjEzNTQ2NTE0ODF9.14AwWVV2B3OiQaZ6SxQHTM41q-H9FSMkKEHttQOBakL2Idys8Z3cH21TkF0AhnIfzEBd728OOuBgfqfPYQnzlWaFvSa6Z1oKlLy663QOEmvPPv593GkO5rbVbSnFaLv0-6I7V2X6kz2iiDyUEACAXgPUHIvClNRxM4GtSmNHBnUjHeSUg7Ji4g02Acoi1glYzj_-JirCgHRxqIRSWTx2dwxQHMCZovE9bIEgK_6O2kkHh2oppHSeXSL3QxzDfTggdJkcUIe99aq3ZFBPS_a2pi95AH-bXVcccj5XJoTi9_NUKZj4vGkCfUt-zjyEbZf_ykOheKpdjYlADBi3MPHNKQ'
                }
            }
            
            function GetWorkspaceByName($workspaceName) {
                # Get workspaces    
                $getWorkspacesUrl = "{0}/workspaces" -f $global:baseUrl
                $workspaces = (Invoke-RestMethod -Headers $global:fabricHeaders -Uri $getWorkspacesUrl -Method GET).value
            
                # Try to find the workspace by display name
                $workspace = $workspaces | Where-Object {$_.DisplayName -eq $workspaceName}
            
                return $workspace
            }
            
            function GetErrorResponse($exception) {
                # Relevant only for PowerShell Core
                $errorResponse = $_.ErrorDetails.Message
            
                if(!$errorResponse) {
                    # This is needed to support Windows PowerShell
                    $result = $exception.Response.GetResponseStream()
                    $reader = New-Object System.IO.StreamReader($result)
                    $reader.BaseStream.Position = 0
                    $reader.DiscardBufferedData()
                    $errorResponse = $reader.ReadToEnd();
                }
            
                return $errorResponse
            }
            
            try {
                SetFabricHeaders
            
                $workspace = GetWorkspaceByName $workspaceName 
                
                # Verify the existence of the requested workspace
            	if(!$workspace) {
            	  Write-Host "A workspace with the requested name was not found." -ForegroundColor Red
            	  return
            	}
            	
                # Commit to Git
                Write-Host "Committing all changes from workspace '$workspaceName' to Git."
            
                $commitToGitUrl = "{0}/workspaces/{1}/git/commitToGit" -f $global:baseUrl, $workspace.Id
            
                $commitToGitBody = @{ 		
                    mode = "All"
                    comment = $commitMessage
                } | ConvertTo-Json
            
                $commitToGitResponse = Invoke-WebRequest -Headers $global:fabricHeaders -Uri $commitToGitUrl -Method POST -Body $commitToGitBody
            
                $operationId = $commitToGitResponse.Headers['x-ms-operation-id']
                $retryAfter = $commitToGitResponse.Headers['Retry-After']
                Write-Host "Long Running Operation ID: '$operationId' has been scheduled for committing changes from workspace '$workspaceName' to Git with a retry-after time of '$retryAfter' seconds." -ForegroundColor Green
            
            } catch {
                $errorResponse = GetErrorResponse($_.Exception)
                Write-Host "Failed to commit changes from workspace '$workspaceName' to Git. Error response: $errorResponse" -ForegroundColor Red
            }            
            
            
          azPSVersion: "latest"       
            
