name: AzureLoginSample

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup
            $commitToGitUrl = "https://api.fabric.microsoft.com/v1/workspaces/654d6099-5fef-4a37-90b2-c07d16f3f88a/git/commitToGit"
            
            $fabricToken = (Get-AzAccessToken).Token
            
            $commitToGitBody = @{
            mode = "All"
            comment = "Saving"
            } | ConvertTo-Json

           $global:fabricHeaders = @{
           'Content-Type' = "application/json"
           'Authorization' = "Bearer {0}" -f $fabricToken
            }
            $result = (Invoke-RestMethod -Headers $global:fabricHeaders -Uri $commitToGitUrl -Method POST -Body $commitToGitBody)
            
            echo $result
            
          azPSVersion: "latest"       
            
