name: Deploy on File Upload

on:
  push:
    paths:
      - 'cp_fabric_lakehouse/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run PowerShell script
      run: |
        pwsh -file ./.github/workflows/OneLake-Lakehouse-Upload.ps1

