name: Fabric API Call

on:
  push:
    branches:
      - main
    path:
      - cp_fabric_lakehouse/**
    paths-ignore:
      - .github/**
      - dest/**
      - deploy/**
      
jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        az login --username $AZURE_USERNAME --password $AZURE_PASSWORD

    - name: Set up PowerShell
      uses: actions/setup-powershell@v1

    - name: Run PowerShell script
      run: |
        pwsh -file /.github/workflows/OneLake-Lakehouse-Upload.ps1
