name: Deploy to UAT after Merge

on:
  pull_request:
    types: [closed]
  path:
    deploy/**
  paths-ignore:
    .github/**
    

jobs:
  deploy_to_uat_after_merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'uat'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        env:
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          az login --username $AZURE_USERNAME --password $AZURE_PASSWORD
          
          echo "::set-env name=AZURE_ACCESS_TOKEN::$(az account get-access-token --resource 'https://api.fabric.microsoft.com' --query 'accessToken' -o tsv)"
          echo "Access Token: ${{ env.AZURE_ACCESS_TOKEN }}"

      - name: Print Access Token
        run: |
          echo "${{ env.AZURE_ACCESS_TOKEN }}"

      - name: Use Access Token in Workflow
        run: |
          echo "Access Token: ${{ env.AZURE_ACCESS_TOKEN }}"
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v33
      
      - name: Make API Call
        env:
          ID_TOKEN: ${{ secrets.MYID_TOKEN }}
          AZURE_ACCESS_TOKEN: ${{ env.AZURE_ACCESS_TOKEN }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            stackfile=$(echo $file | cut -f2 -d'/')
            parameter_value=$(cat deploy/$stackfile)
            curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' \
              --header 'Content-Type: application/json' \
              --header 'Host: graph.microsoft.com' \
              --header "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
              --data "$parameter_value"
          done
