name: Fabric API Call

on:
  push:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make API Call.
      env:
        ID_TOKEN: ${{ secrets.MYID_TOKEN }}
      run: |
       
        #$tokenval = (Get-AzAccessToken).Token
        echo $ID_TOKEN
        curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' --header 'Content-Type: application/json' --header 'Host: graph.microsoft.com' --header 'Authorization: Bearer $ID_TOKEN' \
        --data '{
          "displayName":"test_sp5",
          "description":"test desc" }'
      
