name: Fabric API Call

on:
  push:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Make API Call.
      env:
        ID_TOKEN: ${{ secrets.MYID_TOKEN }}
    

      run: |
       
        curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' \
        --header 'Content-Type: application/json' \
        --header 'Host: graph.microsoft.com' \
        --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCIsImtpZCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81NWVhNjE5Ni03MGI5LTQ0MTEtOTJmNS0wNGE1NDc5MWYxMjAvIiwiaWF0IjoxNzE1NzA1MDYwLCJuYmYiOjE3MTU3MDUwNjAsImV4cCI6MTcxNTcwOTMwMywiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhXQUFBQUtKQVlqMWRGUjQ0czhRbXlNZVZ0QUpFNlJncm4yMGUvQTcxSUw2ODdpUFpUem5RUGN1UzVlazI4MUN2NjVKK0kiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiMTk1MGEyNTgtMjI3Yi00ZTMxLWE5Y2YtNzE3NDk1OTQ1ZmMyIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJZYWRhdiIsImdpdmVuX25hbWUiOiJHb3BhbCIsImdyb3VwcyI6WyI4ODhmOTUwOS00MjdjLTQ3ZDItODlkNy0zNzQ3OGZhNmYyMDgiLCIzYTMyMDY2Ni0yYjMxLTQ1MmMtOTlmNS0zNDg5YjU4Nzc0MWYiLCI3NWFlZjliZS1hYThjLTQyOWMtYTM5ZC0xNzc5NzkxZTk3OGQiXSwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjQwNToyMDE6MzAxNjo4YTFjOjM0ZmQ6OGU3OTplNzA3OmMzYzEiLCJuYW1lIjoiWWFkYXYsIEdvcGFsIiwib2lkIjoiMjUwMjRjMTAtNGY3Mi00MmI4LTgyYzItOGI1NDg5N2NkMWM3IiwicHVpZCI6IjEwMDMyMDAwOEVBRkE3NDgiLCJwd2RfZXhwIjoiNDIyOTYzIiwicHdkX3VybCI6Imh0dHBzOi8vcG9ydGFsLm1pY3Jvc29mdG9ubGluZS5jb20vQ2hhbmdlUGFzc3dvcmQuYXNweCIsInJoIjoiMC5BVnNBbG1IcVZibHdFVVNTOVFTbFI1SHhJRVpJZjNrQXV0ZFB1a1Bhd2ZqMk1CUDVBSEkuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiUHRUdnVRSjhqa2pjcjlCODlKNHQtUXlWYTFBMXNHVTNrbWd5M19YTkpOVSIsInRpZCI6IjU1ZWE2MTk2LTcwYjktNDQxMS05MmY1LTA0YTU0NzkxZjEyMCIsInVuaXF1ZV9uYW1lIjoiZ29wYWwueWFkYXZAc3RyYXRhY2VudC5jb20iLCJ1cG4iOiJnb3BhbC55YWRhdkBzdHJhdGFjZW50LmNvbSIsInV0aSI6IkFIQnk1aDNxZmtxNF9ia1NpOWRHQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2FlIjoiMSIsInhtc19jYyI6WyJDUDEiXSwieG1zX2ZpbHRlcl9pbmRleCI6WyI5MSJdLCJ4bXNfcmQiOiIwLjQyTGxZQlJpakFZQSIsInhtc19zc20iOiIxIiwieG1zX3RjZHQiOjEzNTQ2NTE0ODF9.Yoj8HOZy5xV2LONa4l04EsZ73c9LdUsz3DwM1Ixgk4GMZN1gj3MAaNPkaNx1nKliktp1dHp5znQIyKmUKFGtqQuCLgVNPVxXf8VuNmntBn-sjWB0B42WZnoLEpOWoLymwS_aegETmV0Qib2aOTvVsRMMDMyp9ZmoHDo7HrDA17XMQ8aaybMoDJoaD8Vm9tGeAXt4g_5JlKiMfdLn_rhiGL8QSnM3SSk5odR76jfxuN8_qMUfkMcda7GdualvM4FiqYXK-jWIyqKPpvzJSDnCcs-oIuUqUATPUlchz3SfDA_x4_9MD5NJ49zVLLW29EuqXAPS-X4yJBtkk01fiLquwA' \
        --data '{
          "displayName":"test_sp2",
          "description":"test desc" }'
