name: Fabric API Call

on:
  push:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        
      run: |
        az login --username $AZURE_USERNAME --password $AZURE_PASSWORD
        ACCESS_TOKEN=$(az account get-access-token --resource "https://api.fabric.microsoft.com" --query "accessToken" -o tsv)
        echo $(az account get-access-token --resource "https://api.fabric.microsoft.com" --query "accessToken" -o tsv) 
        #token=$(az account get-access-token | grep accessToken | cut -d: -f2 | cut -d, -f1 | cut -d'"' -f2)
        echo "Azure Access Tokens: $ACCESS_TOKEN"
        
        curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' \
        --header 'Content-Type: application/json' \
        --header 'Host: graph.microsoft.com' \
        --header 'Authorization: Bearer $(az account get-access-token --resource "https://api.fabric.microsoft.com" --query "accessToken" -o tsv)' \
        --data '{
          "displayName":"notebook-12",
          "description":"test desc"
        }'
        
    - name: Make API Call.
      env:
        ID_TOKEN: ${{ secrets.MYID_TOKEN }}
    

      run: |
       
        curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' \
        --header 'Content-Type: application/json' \
        --header 'Host: graph.microsoft.com' \
        --header 'Authorization: Bearer ${{ env.ID_TOKEN }}' \
        --data '{
          "displayName":"notebook-9",
          "description":"test desc"
        }'
