name: Fabric API Call

on:
  push:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        az login --username $AZURE_USERNAME --password $AZURE_PASSWORD
        ACCESS_TOKEN=$(az account get-access-token --resource "https://api.fabric.microsoft.com" --query "accessToken" -o tsv)
        echo "::set-env name=AZURE_ACCESS_TOKEN::$(az account get-access-token --resource "https://api.fabric.microsoft.com" --query "accessToken" -o tsv)"
        echo "Access Token: ${{ env.AZURE_ACCESS_TOKEN }}"
        #=============
    - name: Print Access Token
      run: |
        echo "${{ steps.access_token.outputs.token }}"
    - name: Save Access Token to File
      run: |
        echo "${{ steps.access_token.outputs.token }}" > access_token.txt
    - name: Use Access Token in Workflow
      run: |
        echo "Access Token: ${{ env.AZURE_ACCESS_TOKEN }}"
        #--------------

        
        curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' \
        --header 'Content-Type: application/json' \
        --header 'Host: graph.microsoft.com' \
        --header 'Authorization: Bearer ${{ env.AZURE_ACCESS_TOKEN }}' \
        --data '{
          "displayName":"Moodys",
          "description":"test desc"
        }'
        
    - name: Make API Call.
      env:
        ID_TOKEN: ${{ secrets.MYID_TOKEN }}
    

      run: |
       
        curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' \
        --header 'Content-Type: application/json' \
        --header 'Host: graph.microsoft.com' \
        --header 'Authorization: Bearer ${{ env.ID_TOKEN }}' \
        --data (cat deploy/notebook.py)

        cat deploy/notebook.py
        #--data '{
        #  "displayName":"Moodys-1",
        #  "description":"test desc"
        #}'
