name: Fabric API Call

on:
  push:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        MYCREDS: $(az login --username $AZURE_USERNAME --password $AZURE_PASSWORD)
      run: |
        #MYCREDS = $(az login --username $AZURE_USERNAME --password $AZURE_PASSWORD)
        echo "mycreds are $MYCREDS"
        
    - name: Make API Call.
      env:
        ID_TOKEN: ${{ secrets.MYID_TOKEN }}
    

      run: |
       
        curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' \
        --header 'Content-Type: application/json' \
        --header 'Host: graph.microsoft.com' \
        --header 'Authorization: Bearer ${{ env.ID_TOKEN }}' \
        --data '{
          "displayName":"notebook-3",
          "description":"test desc"
        }'
