name: Fabric API Call

on:
  push:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        
      run: |
        az login --username $AZURE_USERNAME --password $AZURE_PASSWORD
        #token=$(az account get-access-token | grep accessToken)
        #access_token=$(az account get-access-token --query accessToken -o tsv)
        ACCESS_TOKEN=$(az account get-access-token --resource "https://api.fabric.microsoft.com" --query "accessToken" -o tsv)
        token=$(az account get-access-token | grep accessToken | cut -d: -f2 | cut -d, -f1 | cut -d'"' -f2)
        echo "Azure Access Token: $ACCESS_TOKEN"
        echo "Token $token"
        #token1="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCIsImtpZCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81NWVhNjE5Ni03MGI5LTQ0MTEtOTJmNS0wNGE1NDc5MWYxMjAvIiwiaWF0IjoxNzE1NzExNDIwLCJuYmYiOjE3MTU3MTE0MjAsImV4cCI6MTcxNTcxNjc1MiwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhXQUFBQTdNQ0NOZUpJWVIyMDgwUGFVd1ZYaFJSdU42VWVaVklFUG5UTno5V2FnQ3NabTVoaDNDNmM3TlZQdzZaUTFOM1AiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJZYWRhdiIsImdpdmVuX25hbWUiOiJHb3BhbCIsImdyb3VwcyI6WyI4ODhmOTUwOS00MjdjLTQ3ZDItODlkNy0zNzQ3OGZhNmYyMDgiLCIzYTMyMDY2Ni0yYjMxLTQ1MmMtOTlmNS0zNDg5YjU4Nzc0MWYiLCI3NWFlZjliZS1hYThjLTQyOWMtYTM5ZC0xNzc5NzkxZTk3OGQiXSwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiNC4yMjQuMTYwLjIiLCJuYW1lIjoiWWFkYXYsIEdvcGFsIiwib2lkIjoiMjUwMjRjMTAtNGY3Mi00MmI4LTgyYzItOGI1NDg5N2NkMWM3IiwicHVpZCI6IjEwMDMyMDAwOEVBRkE3NDgiLCJwd2RfZXhwIjoiNDE2NjAzIiwicHdkX3VybCI6Imh0dHBzOi8vcG9ydGFsLm1pY3Jvc29mdG9ubGluZS5jb20vQ2hhbmdlUGFzc3dvcmQuYXNweCIsInJoIjoiMC5BVnNBbG1IcVZibHdFVVNTOVFTbFI1SHhJRVpJZjNrQXV0ZFB1a1Bhd2ZqMk1CUDVBSEkuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiUHRUdnVRSjhqa2pjcjlCODlKNHQtUXlWYTFBMXNHVTNrbWd5M19YTkpOVSIsInRpZCI6IjU1ZWE2MTk2LTcwYjktNDQxMS05MmY1LTA0YTU0NzkxZjEyMCIsInVuaXF1ZV9uYW1lIjoiZ29wYWwueWFkYXZAc3RyYXRhY2VudC5jb20iLCJ1cG4iOiJnb3BhbC55YWRhdkBzdHJhdGFjZW50LmNvbSIsInV0aSI6IlI1WmNPT0ZlUTBDX3dZeWRMbTl6QUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2FlIjoiMSIsInhtc19jYyI6WyJDUDEiXSwieG1zX2ZpbHRlcl9pbmRleCI6WyI5MSJdLCJ4bXNfcmQiOiIwLjQyTGxZQlJpakFZQSIsInhtc19zc20iOiIxIiwieG1zX3RjZHQiOjEzNTQ2NTE0ODF9.DTKn3TLI9HqVJ3wyVQtsEFGkhkDGlP_Da3zzdmKVNS9SQsn3mibNhLwbANBv9rpew0ewiDzlgu4pQiPK1F_bU2Bs-2SZvDaBPkeA6n9ntCVvoeHJ0skvSuvvcMbL6n1E5zLPWwwXLNSjlNRmOquy4CjrG39ilwTqO6O10nVv_UTlODzhP-2ua3lunNgKg5LIFfPOkj-8PKnM6yeEE-7JV6dt0oGZNT5m81E0Lr6316SQGETdkclmiyTTodKAXQlBxI4haJXADGQlVl8GJtA2Vl8dVvBiZeOT_XMYoSMxrjGAQ8MRSZ7StuF3MuR9BSK6H3CxtzVtpMW1YeFU1Cozaw"
        curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' \
        --header 'Content-Type: application/json' \
        --header 'Host: graph.microsoft.com' \
        --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCIsImtpZCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCJ9.eyJhdWQiOiJodHRwczovL2FwaS5mYWJyaWMubWljcm9zb2Z0LmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzU1ZWE2MTk2LTcwYjktNDQxMS05MmY1LTA0YTU0NzkxZjEyMC8iLCJpYXQiOjE3MTU3MjA3NjgsIm5iZiI6MTcxNTcyMDc2OCwiZXhwIjoxNzE1NzI1MTI4LCJhY2N0IjowLCJhY3IiOiIxIiwiYWlvIjoiQVRRQXkvOFdBQUFBSGZzY2lpd09zUWp2R2xGM2pTY1FTVnpESVF2NXVuSFBQOTlhUzg1T3J5SzVUYUJDZlVONnc3VGtrb2s3Z0kxMiIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IllhZGF2IiwiZ2l2ZW5fbmFtZSI6IkdvcGFsIiwiaXBhZGRyIjoiNC4yMjQuMTYwLjIiLCJuYW1lIjoiWWFkYXYsIEdvcGFsIiwib2lkIjoiMjUwMjRjMTAtNGY3Mi00MmI4LTgyYzItOGI1NDg5N2NkMWM3IiwicHVpZCI6IjEwMDMyMDAwOEVBRkE3NDgiLCJwd2RfZXhwIjoiNDA3MjU1IiwicHdkX3VybCI6Imh0dHBzOi8vcG9ydGFsLm1pY3Jvc29mdG9ubGluZS5jb20vQ2hhbmdlUGFzc3dvcmQuYXNweCIsInJoIjoiMC5BVnNBbG1IcVZibHdFVVNTOVFTbFI1SHhJQWtBQUFBQUFBQUF3QUFBQUFBQUFBRDVBSEkuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiZWk3NlBORFdSMjZZTTdydWFMVkFjajdxcmdxaWF5dU1tYU0wNTd2MWhHVSIsInRpZCI6IjU1ZWE2MTk2LTcwYjktNDQxMS05MmY1LTA0YTU0NzkxZjEyMCIsInVuaXF1ZV9uYW1lIjoiZ29wYWwueWFkYXZAc3RyYXRhY2VudC5jb20iLCJ1cG4iOiJnb3BhbC55YWRhdkBzdHJhdGFjZW50LmNvbSIsInV0aSI6IkFKMmhnbEpyZ0UtTDlQRHQ4QXB6QUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2MiOlsiQ1AxIl0sInhtc19wbCI6ImVuLVVTIn0.Q3zHtNpMdEOrX0pI9wUvH_P2PMm2KRqUJcq2Yu19dH91yucmfbuwRveBjUEigmLd5SipQsBVoqniqeB3kqNPTeP_th2p0isVma3Y1dpWdlEEaQqkBS9AOhzlHkqLTUgfwYCYjoYbdYFYsSsGRlqHzO1EDL5iL175KG4DysbP216-iux0OHzOP2Ojtjk-tqjsejZOISz85Bz2EDXkPrDFr-9HEUjPnpdMM1QFwhskBTJQV6U7W5MQJUFWlzO4O3I4v6AhiXTC_8d1KpooDqcYdSa9HXUsUqs3gEjNr7bGRerDSaCaZvYJ1NXVsqtn3LXtN6UOi6GZ-D8R2wGacVOHrg' \
        --data '{
          "displayName":"notebook-5",
          "description":"test desc"
        }'
        
    - name: Make API Call.
      env:
        ID_TOKEN: ${{ secrets.MYID_TOKEN }}
    

      run: |
       
        curl --location 'https://api.fabric.microsoft.com/v1/workspaces/029ea194-7a2f-492e-8fa9-d1e471195c57/notebooks' \
        --header 'Content-Type: application/json' \
        --header 'Host: graph.microsoft.com' \
        --header 'Authorization: Bearer ${{ env.ID_TOKEN }}' \
        --data '{
          "displayName":"notebook-6",
          "description":"test desc"
        }'
